DAYS = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
)

STATE = (
    ("Andhra Pradesh", "Andhra Pradesh"),
    ("Arunachal Pradesh", "Arunachal Pradesh"),
    ("Assam", "Assam"),
    ("Bihar", "Bihar"),
    ("Chhattisgarh", "Chhattisgarh"),
    ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli"),
    ("Daman and Diu", "Daman and Diu"),
    ("Delhi", "Delhi"),
    ("Goa", "Goa"),
    ("Gujarat", "Gujarat"),
    ("Haryana", "Haryana"),
    ("Himachal Pradesh", "Himachal Pradesh"),
    ("Jammu and Kashmir", "Jammu and Kashmir"),
    ("Jharkhand", "Jharkhand"),
    ("Karnataka", "Karnataka"),
    ("Kerala", "Kerala"),
    ("Madhya Pradesh", "Madhya Pradesh"),
    ("Maharashtra", "Maharashtra"),
    ("Manipur", "Manipur"),
    ("Meghalaya", "Meghalaya"),
    ("Mizoram", "Mizoram"),
    ("Nagaland", "Nagaland"),
    ("Orissa", "Orissa"),
    ("Puducherry", "Puducherry"),
    ("Punjab", "Punjab"),
    ("Rajasthan", "Rajasthan"),
    ("Sikkim", "Sikkim"),
    ("Tamil Nadu", "Tamil Nadu"),
    ("Telangana", "Telangana"),
    ("Tripura", "Tripura"),
    ("Uttar Pradesh", "Uttar Pradesh"),
    ("Uttarakhand", "Uttarakhand"),
    ("West Bengal", "West Bengal")
)

EVENT_TYPE = (
    ("Campus", "Campus"),
    ("Charity", "Charity"),
    ("Corporate", "Corporate"),
    ("Fashion", "Fashion"),
    ("Kids Party", "Kids Party"),
    ("Wedding", "Wedding"),
    ("Private Party", "Private Party"),
    ("Inauguration", "Inauguration"),
    ("Exhibition", "Exhibition"),
    ("Religion", "Religion"),
    ("Promotion", "Promotion"),
    ("Concert", "Concert")
)

COSTUME = (
    ("Formal", "Formal"),
    ("Semi Formal", "Semi Formal"),
    ("Casual", "Casual"),
    ("Traditional", "Traditional"),
    ("Party Wear", "Party Wear")
)

ANCHOR_TYPE = (
    ("EMCEE", "EMCEE"),
    ("ANCHOR", "ANCHOR"),
    ("VJ", "VJ"),
    ("ACTRESS", "ACTRESS"),
    ("MODEL", "MODEL"),
    ("RJ", "RJ"),
    ("ARTIST", "ARTIST"),
    ("ACTOR", "ACTOR")
)