# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0002_auto_20170317_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
