# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0005_anchorbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorbooking',
            name='function_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='function_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='function_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='function_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='function_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='function_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
