# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0010_auto_20170319_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorbooking',
            name='about_event',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='costume',
            field=models.CharField(choices=[(b'Formal', b'Formal'), (b'Semi Formal', b'Semi Formal'), (b'Casual', b'Casual'), (b'Traditional', b'Traditional'), (b'Party Wear', b'Party Wear')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='event_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='event_type',
            field=models.CharField(choices=[('SHOW', 'SHOW'), ('CAMPUS', 'CAMPUS'), ('KIDS PARTY', 'KIDS PARTY'), ('PRIVATE PARTY', 'PRIVATE PARTY'), ('INAUGURATION', 'INAUGURATION'), ('CORPRATE', 'CORPRATE'), ('PROMOTIONS', 'PROMOTIONS'), ('EXIBITIONS', 'EXIBITIONS'), ('FASHION SHOW', 'FASHION SHOW'), ('WEDDING', 'WEDDING')], default='Campus', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchorbooking',
            name='event_venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
