# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0011_auto_20170319_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorbooking',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
