# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0012_anchorbooking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorbooking',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
