# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfservice', '0013_anchorbooking_razorpay_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.CharField(choices=[(b'EMCEE', b'EMCEE'), (b'ANCHOR', b'ANCHOR'), (b'VJ', b'VJ'), (b'ACTRESS', b'ACTRESS'), (b'MODEL', b'MODEL'), (b'RJ', b'RJ'), (b'ARTIST', b'ARTIST')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='anchorlanguage',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MALAYALAM', 'MALAYALAM'), ('TAMIL', 'TAMIL'), ('KANNADA', 'KANNADA'), ('PUNJABI', 'PUNJABI'), ('TELUGU', 'TELUGU'), ('MARATHI', 'MARATHI'), ('HINDI', 'HINDI'), ('ARABIC', 'ARABIC'), ('FRENCH', 'FRENCH')], max_length=50),
        ),
    ]
