# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0014_auto_20170321_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.SlugField(choices=[(b'EMCEE', b'EMCEE'), (b'ANCHOR', b'ANCHOR'), (b'VJ', b'VJ'), (b'ACTRESS', b'ACTRESS'), (b'MODEL', b'MODEL'), (b'RJ', b'RJ'), (b'ARTIST', b'ARTIST')], default='ANCHOR'),
        ),
    ]
