# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0015_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.ManyToManyField(blank=True, to='selfservice.AchorType'),
        ),
    ]
